<?php if (count($flash) > 0): ?>
  <ul>
  <?php foreach ($flash as $messages): ?>
      <?php foreach ($messages as $message): ?>
          <li><?= $message ?></li>
      <?php endforeach ?>
  <?php endforeach ?>
  </ul>
<?php endif ?>

<?php if ($currentUser): ?>
    <div><?= $currentUser['name'] ?></div>
    <form action="/session" method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Sign Out">
    </form>
<?php else: ?>
    <form action="/session" method="post">
        <label>
            Login:
            <input type="text" required name="user[name]" value="">
        </label>
        <label>
            Password:
            <input type="password" required name="user[password]" value="">
        </label>
        <input type="submit" value="Sign In">
    </form>
<?php endif; ?>